;;; magit-difftastic-lazy-test.el --- Lazy section tests -*- lexical-binding: t; -*-

;;; Commentary:
;; Real Magit section trees with deferred UI delivery and isolated processes.

;;; Code:

(eval-and-compile
  (let ((load-path (cons (expand-file-name
                         "test" (file-name-directory
                                 (locate-library "magit-difftastic")))
                        load-path)))
    (require 'magit-difftastic-test)
    (require 'magit-difftastic-async-test)))

(defconst dst-lazy-test--render-raw
  (symbol-function 'magit-difftastic--render-raw)
  "Synchronous fixture renderer, independent of UI test stubs.")

(defmacro dst-lazy-test--isolated (&rest body)
  "Evaluate BODY with isolated caches, scheduler, and show advice."
  (declare (indent 0) (debug t))
  `(dst-async-test--isolated
     (let ((magit-difftastic-lazy t)
           (magit-difftastic-cache t)
           (magit-difftastic--cache (make-hash-table :test #'equal))
           (magit-difftastic--syntax-cache (make-hash-table :test #'equal))
           (magit-difftastic--render-cache nil)
           (magit-difftastic-default-rendering 'difftastic)
           (magit-difftastic-display "side-by-side-show-both")
           (magit-difftastic-width 120)
           (magit-difftastic-align-columns nil)
           (magit-difftastic-syntax-highlight nil)
           (had-advice (advice-member-p #'magit-difftastic--lazy-show
                                        'magit-section-show)))
       (unwind-protect
           (progn
             (advice-add 'magit-section-show :after #'magit-difftastic--lazy-show)
             ,@body)
         (unless had-advice
           (advice-remove 'magit-section-show #'magit-difftastic--lazy-show))))))

(defmacro dst-lazy-test--fixture (&rest body)
  "Evaluate BODY with a changed repository and deferred render callbacks."
  (declare (indent 0) (debug t))
  `(progn
     (skip-unless dst-test--have-tools)
     (dst-lazy-test--isolated
       (dst-test--with-repo
           `(("sample.txt" . ,dst-test--old))
           `(("sample.txt" . ,dst-test--new))
         (let ((raw (funcall dst-lazy-test--render-raw
                             "sample.txt" magit-difftastic--diff-base 120))
               (metadata
                (with-temp-buffer
                  (should (zerop
                           (apply #'process-file "git" nil t nil
                                  (append (magit-difftastic--raw-args
                                           magit-difftastic--diff-base)
                                          '("--" "sample.txt")))))
                  (buffer-string)))
               requests promotions)
           (should (gethash "sample.txt" (magit-difftastic--parse-raw-info metadata)))
           (should (string-match-p "BRAVO-changed" raw))
           (cl-letf (((symbol-function 'magit-difftastic--async-request)
                      (lambda (&rest args) (push args requests) nil))
                     ((symbol-function 'magit-difftastic--async-promote)
                      (lambda (job) (push job promotions)))
                     ((symbol-function 'magit-difftastic--render-raw)
                      (lambda (&rest _) (ert-fail "Unexpected synchronous render")))
                     ((symbol-function 'magit-difftastic--prewarm)
                      (lambda (&rest _) (ert-fail "Unexpected eager prewarm"))))
             (with-temp-buffer
               (magit-status-mode)
               (setq-local magit-section-cache-visibility nil)
               ,@body)))))))

(defmacro dst-lazy-test--deliver ()
  "Deliver the fixture's render and metadata stages separately."
  `(let ((render (car requests))
         (count (length requests)))
     (should-not (eq (caar render) 'validate))
     (should-not magit-difftastic-syntax-highlight)
     (cl-letf (((symbol-function 'process-file)
                (lambda (&rest _) (ert-fail "Synchronous process in callback"))))
       (funcall (nth 5 render) raw nil)
       (should (= (length requests) (1+ count)))
       (let ((validation (car requests)))
         (should (equal (car validation) (list 'validate (car render))))
         (should (equal (nth 2 validation)
                        (append (magit-difftastic--raw-args
                                 magit-difftastic--diff-base)
                                '("--" "sample.txt"))))
         (should (eq (nth 4 validation) (current-buffer)))
         (should (cl-every
                  (lambda (request)
                    (eq (magit-difftastic--lazy-file-state request) 'pending))
                  magit-difftastic--lazy-requests))
         (should (zerop (hash-table-count magit-difftastic--cache)))
         (funcall (nth 5 validation) metadata nil)
         (should (= (length requests) (1+ count)))))))

(defun dst-lazy-test--tree (&optional position parent-hidden)
  "Insert a real tree with the file at POSITION among three siblings.
Return the file request; nil POSITION inserts only the file.
Non-nil PARENT-HIDDEN initially collapses the file's parent."
  (let ((inhibit-read-only t))
    (magit-insert-section (root)
      (magit-insert-heading "Root")
      (magit-insert-section (unstaged nil parent-hidden)
        (magit-insert-heading "Unstaged")
        (dotimes (i (if position 3 1))
          (if (or (null position) (= i position))
              (magit-difftastic--insert-file-sections
               '("sample.txt") (magit-difftastic--context-unstaged))
            (magit-insert-section (neighbor i)
              (magit-insert-heading (format "Neighbor %d" i))
              (insert (format "untouched body %d\n" i))))))))
  (let (request)
    (maphash (lambda (_section value) (setq request value))
             magit-difftastic--lazy-sections)
    (should request)
    request))

(defun dst-lazy-test--body (section)
  "Return SECTION's body without text properties."
  (buffer-substring-no-properties (oref section content) (oref section end)))

(defun dst-lazy-test--check-tree (section)
  "Assert marker bounds and parent relationships throughout SECTION."
  (dolist (slot '(start content end))
    (let ((marker (slot-value section slot)))
      (should (markerp marker))
      (should (eq (marker-buffer marker) (current-buffer)))))
  (should (<= (point-min) (oref section start) (oref section content)
              (oref section end) (point-max)))
  (let ((previous (oref section content)))
    (dolist (child (oref section children))
      (should (eq (oref child parent) section))
      (should (<= previous (oref child start) (oref child end)
                  (oref section end)))
      (setq previous (oref child end))
      (dst-lazy-test--check-tree child))))

(ert-deftest magit-difftastic-lazy/collapsed-queues-heading-only ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request)))
      (should (= (length requests) 1))
      (should-not (nth 6 (car requests)))
      (should (eq (nth 4 (car requests)) (current-buffer)))
      (should (equal (nth 2 (car requests))
                     (append magit-difftastic--diff-base '("--" "sample.txt"))))
      (should (oref section hidden))
      (should (functionp (oref section washer)))
      (should (equal (dst-lazy-test--body section) ""))
      (should-not (oref section children))
      (should-not promotions)
      (should (zerop (hash-table-count magit-difftastic--syntax-cache)))
      (dst-lazy-test--check-tree magit-root-section))))

(ert-deftest magit-difftastic-lazy/first-expansion-promotes-same-job ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request))
           (job (list 'existing-job)))
      (setf (magit-difftastic--lazy-file-job request) job)
      (magit-section-show section)
      (should-not (oref section hidden))
      (should-not (oref section washer))
      (should (string-match-p "Rendering difftastic" (dst-lazy-test--body section)))
      (should (get-text-property (oref section content) 'magit-difftastic-pending))
      (should-not (invisible-p (oref section content)))
      (should (eq (car promotions) job))
      (should (equal promotions (list job job)))
      (magit-section-hide section)
      (magit-section-show section)
      (should (= (length requests) 1))
      (should (equal promotions (list job job job))))))

(ert-deftest magit-difftastic-lazy/collapsed-completion-caches-without-insertion ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request))
           (before (buffer-string)))
      (dst-lazy-test--deliver)
      (should (eq (magit-difftastic--lazy-file-state request) 'ready))
      (should (equal (buffer-string) before))
      (should (equal (gethash (magit-difftastic--lazy-file-key request)
                             magit-difftastic--cache)
                     (magit-difftastic--lazy-file-output request)))
      (should-not (oref section children))
      (should (zerop (hash-table-count magit-difftastic--syntax-cache)))
      (magit-section-show section)
      (should (eq (magit-difftastic--lazy-file-state request) 'rendered))
      (should (oref section children))
      (should (string-match-p "BRAVO-changed" (dst-lazy-test--body section)))
      (should (= (length requests) 2))
      (should (= (cl-count 'validate requests :key #'caar) 1)))))

(ert-deftest magit-difftastic-lazy/ready-after-collapse-populates-through-show-advice ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request)))
      (magit-section-show section)
      (magit-section-hide section)
      (dst-lazy-test--deliver)
      (should (eq (magit-difftastic--lazy-file-state request) 'ready))
      (should (string-match-p "Rendering difftastic" (dst-lazy-test--body section)))
      (magit-section-show section)
      (should (eq (magit-difftastic--lazy-file-state request) 'rendered))
      (let ((text (buffer-string)) (children (copy-sequence (oref section children))))
        (should children)
        (dotimes (_ 3)
          (magit-section-hide section)
          (magit-section-show section)
          (should (equal (buffer-string) text))
          (should (equal (oref section children) children))))
      (should (= (length requests) 2))
      (should (= (cl-count 'validate requests :key #'caar) 1))
      (should-not (text-property-any (oref section content) (oref section end)
                                     'magit-difftastic-pending t))
      (dst-lazy-test--check-tree magit-root-section))))

(ert-deftest magit-difftastic-lazy/replacement-preserves-neighbors-markers-and-point ()
  (dotimes (position 3)
    (dst-lazy-test--fixture
      (let* ((request (dst-lazy-test--tree position))
             (section (magit-difftastic--lazy-file-section request))
             (neighbors (cl-remove section (oref (oref section parent) children)))
             (texts (mapcar (lambda (s)
                              (buffer-substring-no-properties (oref s start) (oref s end)))
                            neighbors)))
        (magit-section-show section)
        (goto-char (oref (car (last neighbors)) content))
        (let ((saved (point-marker))
              (ends (mapcar (lambda (s) (marker-insertion-type (oref s end)))
                            (magit-section-lineage section t))))
          (unwind-protect
              (progn
                (set-buffer-modified-p nil)
                (dst-lazy-test--deliver)
                (should (= (point) saved))
                (should-not (buffer-modified-p))
                (should (equal ends
                               (mapcar (lambda (s) (marker-insertion-type (oref s end)))
                                       (magit-section-lineage section t)))))
            (set-marker saved nil)))
        (should (eq (magit-difftastic--lazy-file-state request) 'rendered))
        (should (equal texts
                       (mapcar (lambda (s)
                                 (buffer-substring-no-properties (oref s start) (oref s end)))
                               neighbors)))
        (should (= (oref magit-root-section start) (point-min)))
        (should (= (oref magit-root-section end) (point-max)))
        (dst-lazy-test--check-tree magit-root-section)))))

(ert-deftest magit-difftastic-lazy/stale-root-completion-is-ignored ()
  (dst-lazy-test--fixture
    (let* ((old (dst-lazy-test--tree))
           (callback (nth 5 (car requests))))
      (let ((inhibit-read-only t)) (erase-buffer))
      (let* ((new (dst-lazy-test--tree)) (text (buffer-string)))
        (should-not (eq (magit-difftastic--lazy-file-root old)
                        (magit-difftastic--lazy-file-root new)))
        (funcall callback raw nil)
        (should (equal text (buffer-string)))
        (should (eq (magit-difftastic--lazy-file-state old) 'pending))
        (should (eq (magit-difftastic--lazy-file-state new) 'pending))
        (should (zerop (hash-table-count magit-difftastic--cache)))))))

(ert-deftest magit-difftastic-lazy/changed-worktree-completion-is-rejected ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request)))
      (magit-section-show section)
      (dst-test--write "sample.txt" (concat dst-test--new "a size-changing edit\n"))
      (dst-lazy-test--deliver)
      (should (eq (magit-difftastic--lazy-file-state request) 'stale))
      (should (string-match-p "Diff changed" (dst-lazy-test--body section)))
      (should-not (oref section children))
      (should (zerop (hash-table-count magit-difftastic--cache))))))

(ert-deftest magit-difftastic-lazy/process-error-has-visible-placeholder ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request)))
      (magit-section-show section)
      (funcall (nth 5 (car requests)) "process diagnostic" '(:kind exit :code 2))
      (should (eq (magit-difftastic--lazy-file-state request) 'failed))
      (should (string-match-p "Difftastic failed" (dst-lazy-test--body section)))
      (should-not (invisible-p (oref section content)))
      (should-not (oref section children))
      (should (zerop (hash-table-count magit-difftastic--cache))))))

(ert-deftest magit-difftastic-lazy/nil-option-uses-eager-path ()
  (skip-unless dst-test--have-tools)
  (dst-lazy-test--isolated
    (dst-test--with-repo `(("sample.txt" . ,dst-test--old))
        `(("sample.txt" . ,dst-test--new))
      (with-temp-buffer
        (magit-status-mode)
        (let ((magit-difftastic-lazy nil)
              (inhibit-read-only t)
              (prewarm (symbol-function 'magit-difftastic--prewarm))
              calls)
          (cl-letf (((symbol-function 'magit-difftastic--prewarm)
                     (lambda (&rest args) (push args calls) (apply prewarm args)))
                    ((symbol-function 'magit-difftastic--async-request)
                     (lambda (&rest _) (ert-fail "Unexpected lazy request"))))
            (magit-insert-section (root)
              (magit-difftastic--insert-file-sections
               '("sample.txt") (magit-difftastic--context-unstaged))))
          (should (= (length calls) 1))
          (let ((section (car (oref magit-root-section children))))
            (should (oref section hidden))
            (should-not (oref section washer))
            (should (oref section children))
            (should (string-match-p "BRAVO-changed" (dst-lazy-test--body section)))))))))

(ert-deftest magit-difftastic-lazy/real-async-expanded-file ()
  (skip-unless dst-test--have-tools)
  (dst-lazy-test--isolated
    (dst-test--with-repo `(("sample.txt" . ,dst-test--old))
        `(("sample.txt" . ,dst-test--new))
      (with-temp-buffer
        (magit-diff-mode)
        (let* ((request (dst-lazy-test--tree))
               (section (magit-difftastic--lazy-file-section request))
               (job (magit-difftastic--lazy-file-job request)))
          (unwind-protect
              (progn
                (should job)
                (should-not (oref section hidden))
                (dst-async-test--wait
                 (lambda () (memq (magit-difftastic--lazy-file-state request)
                                  '(rendered failed stale))))
                (should (eq (magit-difftastic--lazy-file-state request) 'rendered))
                (should (string-match-p "BRAVO-changed" (dst-lazy-test--body section)))
                (should (oref section children))
                (should-not (magit-difftastic--async-job-buffer job))
                (should (zerop magit-difftastic--async-active))
                (should (zerop (hash-table-count magit-difftastic--async-jobs)))
                (dst-lazy-test--check-tree magit-root-section))
            (magit-difftastic--async-cancel-buffer (current-buffer))))))))

(ert-deftest magit-difftastic-lazy/published-chunk-stages-across-displays ()
  (dolist (display dst-test--displays)
    (ert-info ((format "Lazy staging in %s" display))
      (dst-lazy-test--fixture
        (let ((magit-difftastic-display display)
              (magit-difftastic-line-numbers
               (not (equal display "side-by-side-show-both"))))
          (setq raw (funcall dst-lazy-test--render-raw
                             "sample.txt" magit-difftastic--diff-base 120))
          (let* ((expected (dst-test--git "diff" "--" "sample.txt"))
                 (request (dst-lazy-test--tree))
                 (section (magit-difftastic--lazy-file-section request)))
            (should-not (string-empty-p expected))
            (should (string-empty-p (dst-test--git "diff" "--cached")))
            (magit-section-show section)
            (should (eq (magit-difftastic--lazy-file-state request) 'pending))
            (should-not (oref section children))
            (dst-lazy-test--deliver)
            (should (eq (magit-difftastic--lazy-file-state request) 'rendered))
            (should (= (length (oref section children)) 1))
            (let ((chunk (car (oref section children)))
                  (refreshes 0))
              (should (eq (oref chunk type) 'magit-difftastic-hunk))
              (should (eq (oref chunk parent) section))
              (goto-char (oref chunk content))
              (unless magit-difftastic-line-numbers
                (let ((gutter (get-text-property (point) 'display)))
                  (should (stringp gutter))
                  (should (string-blank-p gutter))
                  (should (looking-at-p "[0-9]"))))
              (cl-letf (((symbol-function 'magit-refresh)
                         (lambda (&rest _) (cl-incf refreshes))))
                (magit-difftastic--stage-chunk-1 chunk))
              (should (= refreshes 1)))
            (should (equal (dst-test--git "diff" "--cached" "--" "sample.txt")
                           expected))
            (should (equal (dst-test--git "show" ":sample.txt") dst-test--new))
            (should (string-empty-p (dst-test--git "diff")))
            (dst-lazy-test--check-tree magit-root-section)))))))

(ert-deftest magit-difftastic-lazy/publication-hides-chunk-bodies ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request))
           (magit-section-initial-visibility-alist '((magit-difftastic-hunk . hide))))
      (magit-section-show section)
      (dst-lazy-test--deliver)
      (should (eq (magit-difftastic--lazy-file-state request) 'rendered))
      (should (oref section children))
      (dolist (chunk (oref section children))
        (should (oref chunk hidden))
        (should (< (oref chunk content) (oref chunk end)))
        (should-not (invisible-p (oref chunk start)))
        (let ((position (marker-position (oref chunk content))))
          (while (< position (oref chunk end))
            (should (invisible-p position))
            (cl-incf position)))))))

(ert-deftest magit-difftastic-lazy/expanded-under-hidden-parent ()
  (dst-lazy-test--fixture
    (magit-diff-mode)
    (let* ((request (dst-lazy-test--tree nil t))
           (section (magit-difftastic--lazy-file-section request))
           (parent (oref section parent))
           (job (list 'background-job)))
      (setf (magit-difftastic--lazy-file-job request) job)
      (should (oref parent hidden))
      (should-not (oref section hidden))
      (should-not (nth 6 (car requests)))
      (should-not promotions)
      (should (equal (dst-lazy-test--body section) ""))
      (magit-section-show parent)
      (should (member job promotions))
      (should (= (length requests) 1))
      (should-not (invisible-p (oref section content)))
      (should (string-match-p "Rendering difftastic" (dst-lazy-test--body section))))))

(ert-deftest magit-difftastic-lazy/ready-output-changed-before-expansion ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request)))
      (dst-lazy-test--deliver)
      (should (eq (magit-difftastic--lazy-file-state request) 'ready))
      (dst-test--write "sample.txt" (concat dst-test--new "later edit\n"))
      (cl-letf (((symbol-function 'process-file)
                 (lambda (&rest _) (ert-fail "Synchronous process on expansion"))))
        (magit-section-show section))
      (should (eq (magit-difftastic--lazy-file-state request) 'stale))
      (should (string-match-p "Diff changed" (dst-lazy-test--body section)))
      (should-not (oref section children))
      (should (= (length requests) 2)))))

(ert-deftest magit-difftastic-lazy/pending-operations-reject-before-original ()
  (dst-lazy-test--fixture
    (let* ((request (dst-lazy-test--tree))
           (section (magit-difftastic--lazy-file-section request))
           called)
      (magit-section-show section)
      (goto-char (oref section content))
      (dolist (advice '(magit-difftastic--stage-advice
                        magit-difftastic--unstage-advice
                        magit-difftastic--discard-advice))
        (should-error (funcall advice (lambda (&rest _) (setq called t)))
                      :type 'user-error)
        (should-not called)))))

(ert-deftest magit-difftastic-lazy/refresh-prunes-both-stage-subscriptions ()
  (dst-lazy-test--fixture
    (let* ((old (dst-lazy-test--tree))
           (render (magit-difftastic--lazy-file-callback old))
           (async-request (symbol-function 'magit-difftastic--async-request))
           new removed)
      (funcall render raw nil)
      (let ((validation (magit-difftastic--lazy-file-validation-callback old)))
        (cl-letf (((symbol-function 'magit-difftastic--async-unsubscribe)
                   (lambda (owner callback) (push (list owner callback) removed)))
                  ((symbol-function 'magit-difftastic--async-request)
                   (lambda (&rest args)
                     (should magit-difftastic--refreshing)
                     (apply async-request args))))
          (should (eq
                   (magit-difftastic--refresh-advice
                    (lambda (value)
                      (let ((inhibit-read-only t)) (erase-buffer))
                      (setq new (dst-lazy-test--tree))
                      value)
                    'refreshed)
                   'refreshed)))
        (should (equal magit-difftastic--lazy-requests (list new)))
        (should (= (length removed) 2))
        (should (member (list (current-buffer) render) removed))
        (should (member (list (current-buffer) validation) removed))
        (let ((text (buffer-string)) (count (length requests)))
          (funcall render raw nil)
          (funcall validation metadata nil)
          (should (= (length requests) count))
          (should (equal text (buffer-string)))
          (should (eq (magit-difftastic--lazy-file-state new) 'pending)))
        (should (zerop (hash-table-count magit-difftastic--cache)))))))

(ert-deftest magit-difftastic-lazy/prune-retains-shared-current-jobs ()
  (let ((subscribe (symbol-function 'magit-difftastic--async-request)))
    (dst-lazy-test--fixture
      (dst-async-test--mocked
        (cl-letf (((symbol-function 'magit-difftastic--async-request) subscribe))
          (let* ((old (dst-lazy-test--tree))
                 (render-job (magit-difftastic--lazy-file-job old))
                 validation-job new)
            (funcall (magit-difftastic--lazy-file-callback old) raw nil)
            (setq validation-job (magit-difftastic--lazy-file-job old))
            (should-not (eq render-job validation-job))
            (magit-difftastic--refresh-advice
             (lambda ()
               (let ((inhibit-read-only t)) (erase-buffer))
               (setq new (dst-lazy-test--tree))
               (should (eq render-job (magit-difftastic--lazy-file-job new)))
               (funcall (magit-difftastic--lazy-file-callback new) raw nil)
               (should (eq validation-job (magit-difftastic--lazy-file-job new)))))
            (should (equal magit-difftastic--lazy-requests (list new)))
            (should (= (hash-table-count magit-difftastic--async-jobs) 2))
            (cl-mapc
             (lambda (job callback)
               (should (magit-difftastic--async-current-p job))
               (should (eq (magit-difftastic--async-job-state job) 'queued))
               (should (equal (magit-difftastic--async-job-subscribers job)
                              (list (list (current-buffer) callback nil)))))
             (list render-job validation-job)
             (list (magit-difftastic--lazy-file-callback new)
                   (magit-difftastic--lazy-file-validation-callback new)))
            (magit-difftastic--lazy-prune)
            (should (= (hash-table-count magit-difftastic--async-jobs) 2))
            (should-not launches)))))))

(provide 'magit-difftastic-lazy-test)
;;; magit-difftastic-lazy-test.el ends here
